@access_token = eyJ1c2VyX2lkIjoiMSIsImV4cGlyZXNfYXQiOiIyMDI1LTEwLTE3VDE3OjIwOjQ0LjMwMzQyOVoifQ==

### Sign Up
POST http://localhost:8080/api/v1/user/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Sign In
POST http://localhost:8080/api/v1/user/signin
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

### Create My Portal Page
POST http://localhost:8080/api/v1/me/portal-pages
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "slug": "good-example-3",
  "title": "Good Example's Portal Page",
  "bio": "Good Example's Portal Page",
  "profile_image_url": "https://example.com/images/good-example.jpg",
  "theme": "dark"
}

### List My Portal Pages
GET http://localhost:8080/api/v1/me/portal-pages
Authorization: Bearer {{access_token}}

### Find My Portal Page By ID
GET http://localhost:8080/api/v1/me/portal-pages/1
Authorization: Bearer {{access_token}}

### Update My Portal Page
PUT http://localhost:8080/api/v1/me/portal-pages/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "slug": "good-example-0",
  "title": "John's Updated Page Happy",
  "bio": "Welcome to my updated page!!!",
  "profile_image_url": "https://example.com/images/john-new.jpg",
  "theme": "dark",
  "links": [
    {
      "title": "My Blog",
      "url": "https://blog.example.com",
      "description": "Check out my blog",
      "icon_url": "https://example.com/icons/blog.png",
      "display_order": 1
    },
    {
      "title": "My Blog",
      "url": "https://blog.example.com",
      "description": "Check out my blog",
      "icon_url": "https://example.com/icons/blog.png",
      "display_order": 2
    }
  ]
}
